name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        environment-file: environment.yml
        activate-environment: smartclip-env
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev python3-dev python3-pip git zip unzip openjdk-11-jdk
        
    - name: Install additional Python dependencies
      run: |
        conda activate smartclip-env
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Initialize buildozer
      run: |
        conda activate smartclip-env
        buildozer init
      continue-on-error: true
    
    - name: Build APK
      run: |
        conda activate smartclip-env
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: smartclip-app-apk
        path: bin/*.apk
        if-no-files-found: warn